// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfeGQgmN4zPpraYLSSuq-vcgtqliHNDpg',
    appId: '1:1667041059:web:0122dd554d17de32aeee96',
    messagingSenderId: '1667041059',
    projectId: 'flutter-test1-83dea',
    authDomain: 'flutter-test1-83dea.firebaseapp.com',
    storageBucket: 'flutter-test1-83dea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOI2KSmes1jMc_ZExdoQQfhiYQ-yzFvlo',
    appId: '1:1667041059:android:ef7ab9e09a6ee844aeee96',
    messagingSenderId: '1667041059',
    projectId: 'flutter-test1-83dea',
    storageBucket: 'flutter-test1-83dea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApUUUDXYTZKZMuaM1l6S8BSxzdvr04ukc',
    appId: '1:1667041059:ios:579025af0ab3f844aeee96',
    messagingSenderId: '1667041059',
    projectId: 'flutter-test1-83dea',
    storageBucket: 'flutter-test1-83dea.appspot.com',
    iosClientId: '1667041059-tfmniauq62pisoul38lpgs0126k145jp.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApUUUDXYTZKZMuaM1l6S8BSxzdvr04ukc',
    appId: '1:1667041059:ios:6a28aba93a9f2b8daeee96',
    messagingSenderId: '1667041059',
    projectId: 'flutter-test1-83dea',
    storageBucket: 'flutter-test1-83dea.appspot.com',
    iosClientId: '1667041059-2ff7cjd69r80v6t2encd8bmtrkoo9qig.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase.RunnerTests',
  );
}
